server:
  port: 8081

spring:
  application:
    name: producer-service
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        linger.ms: 1000
      batch-size: 16384
kafka:
  topic: "topic"